export type MediaType =
  | 'audio'
  | 'document'
  | 'gif'
  | 'image'
  | 'ppic'
  | 'product'
  | 'ptt'
  | 'sticker'
  | 'video'
  | 'thumbnail-document'
  | 'thumbnail-image'
  | 'thumbnail-video'
  | 'thumbnail-link'
  | 'ptv'
  | 'text'
  | 'react'
